### ISSUE TITLE
Error from pip's dependency resolver 

### ISSUE THREAD

**Issue by fionahanington** [dwave-examples/qboost#27]
When running this example with Ocean 4 in Leap IDE, see the following message:
```
Installing collected packages: tabulate, scikit-learn, matplotlib
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-learn 0.8.1 requires scikit-learn>=0.24, but you have scikit-learn 0.23.1 which is incompatible.
Successfully installed matplotlib-3.3.4 scikit-learn-0.23.1 tabulate-0.8.9
```

**Comment by randomir** [comment]
A bit of context, @mcfarljm:

In the LeapIDE we have `imbalanced-learn` preinstalled. We install the latest version (at the time of image build), so we currently have `imbalanced-learn==0.8.1` (the latest version). Since 0.8.0 (Feb 18 2021) they require [`scikit-learn>=0.24`](https://github.com/scikit-learn-contrib/imbalanced-learn/blob/f177b05256fa3e4e556c1a8be0283b721b1bcd86/setup.py#L44).

However, requirements in the repo pin it to 0.23.1:

https://github.com/dwave-examples/qboost/blob/67aba3e2ce70d746195cffafd1baacd99367c5f2/requirements.txt#L2

FWIW, in the latest LeapIDE (test) we also have preinstalled `scikit-learn==1.0` (the latest version).

**Comment by mcfarljm** [comment]
The code does not currently use `imbalanced-learn`, but it is needed for some functionality that I was planning to add.  @randomir , maybe the easiest fix here is to bump `requirements.txt` to `scikit-learn==0.24.2` (tested locally).  And while we're doing that, I suspect we can also remove the python 3.5 handling as well?

I forget the details around why it was necessary to preinstall `imbalanced-learn` before we could add it to `requirements.txt`, but I also seem to recall that a better alternative might be to add it to `.gitpod.yaml`?  If so, maybe that would be preferable to preinstalling `imbalanced-learn`, given that we're not currently using it in any other repos?
